### PR TITLE
Update parsing calls to latest YAJL API

### PR DESCRIPTION
**Pull request by jarz**
Lloyd has made some breaking API changes in YAJL. This commit uses the newest method calls, structs, etc.

### CODE REVIEW

**Comment by kdopen** [comment]
Thanks jarz. We have a series of commits rolling though the master branch over the next few days and will look at your request when they are complete.

Also, we might not necessarily tie ourselves to the absolute latest version of YAJL until after the 1.0 release.

**Comment by panda-z** [comment]
Looks good to me. I'm using yajl 2.0.4.

**Comment by kdopen** [comment]
We are specifying 1.0.12-2 as our compatible version of yajl, being the version which ships with Ubuntu 12.04 according to pkgs.org. I have not yet looked at yajl-2.x to see how different it is from the 1.x series.

Any changes to support later versions would need to be conditionally compiled in. Does yajl provide something like a YAJL_VERSION symbol which can be tested for compatibility?

**Comment by jarz** [comment]
yajl_version.h defines YAJL_VERSION and a function that returns the version as well. The downside is that we'd need to include that file as well or replace the yajl_common.h include with yajl_version.h.

**Comment by panda-z** [comment]
@jarz yajl_version.h is the new added header file in version 2.x, we can not include it in version 1.x

**Comment by kdopen** [comment]
Which means that the CMake script will need to try and find yajl_version.h and then pass in a flag to indicate whether version 1.x or 2.x is being used. This can then be tested in the code to conditionally include the header file.

Compatibility changes will have to be conditioned on something like

```
#ifndef YAJL_VERSION_2_FOUND
   .. version 1.x code
#else
#   if YAJL_VERSION == ...
  ...
#   else
  ...
#   endif
#endif
```

**Comment by kdopen** [comment]
Strictly speaking, we were not planning to support yajl 2.x - or at least not initially. If there is sufficient interest in, or advantage to, moving to 2.x we can certainly consider it.

One big motivation would be that the 1.x branch was being deprecated and might disappear.

**Comment by ericblade** [comment]
"YAJL 2 is somewhere between 20%-35% faster in its raw parsing performance." from the yajl changelog.  Sounds at least worth experimenting with.

**Comment by kuta42** [comment]
I think creating a Jira at jira.openwebosproject.org is the way requests for component version upgrades should be handled. @jarz: would you be willing to do this? If not, then I'd like to create it for you.

**Comment by panda-z** [comment]
@kuta42 : I've created one for @jarz :-)

**Pull request closed without merging**
